package dadosGerais;

import java.util.ArrayList;

import modelosDados.CorrelacaoColunasArquivos;

public class CorrelacaoArquivosNovasSolicitacoes {

	public ArrayList<CorrelacaoColunasArquivos> obterCorrelacaoEntreArquivos(String consultaOuExame)
	{
		ArrayList<CorrelacaoColunasArquivos> correlacao = new ArrayList<CorrelacaoColunasArquivos>();
		
		if(consultaOuExame.equals("Exame"))
		{
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getIndice(), ParametrosArquivoNovasSolicitacoesExame.INDICE_COLUNA_COD_PACIENTE.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoNovasSolicitacoesExame.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoNovasSolicitacoesExame.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getIndice(), ParametrosArquivoNovasSolicitacoesExame.INDICE_COLUNA_DATA_INCLUSAO.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getIndice(), ParametrosArquivoNovasSolicitacoesExame.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getFormato()));
		}
		else if(consultaOuExame.equals("Consulta"))
		{
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getIndice(), ParametrosArquivoNovasSolicitacoesConsulta.INDICE_COLUNA_COD_PACIENTE.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_COD_PACIENTE.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoNovasSolicitacoesConsulta.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_ESPECIALIDADE_EXAME.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoNovasSolicitacoesConsulta.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_CID.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getIndice(), ParametrosArquivoNovasSolicitacoesConsulta.INDICE_COLUNA_DATA_INCLUSAO.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_DATA_INCLUSAO.getFormato()));
			correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getIndice(), ParametrosArquivoNovasSolicitacoesConsulta.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getTipo(), ParametrosArquivoNovasSolicitacoesConsolidadoOld.INDICE_COLUNA_UNIDADES_CAMPINAS.getFormato()));
		}
		
		return correlacao;
	}
	
}
