package dadosGerais;

import java.util.ArrayList;

import modelosDados.CorrelacaoColunasArquivos;

public class CorrelacaoArquivosDemandaReprimida {

	/*
	 * Classe criada para correlacionar a posição das colunas dos arquivos baixados a partir do SIRESP.
	 * Os arquivos de Novas Solicitações para EXAME e para CONSULTA possuem estruturas ligeiramente distintas. Portanto a ideia aqui é manter a correlação das colunas 
	 * de forma a melhorar o processo de escrita no arquivo final do Novas Solicitações de cada uniadade. 
	 */
	
	public ArrayList<CorrelacaoColunasArquivos> obterCorrelacaoEntreArquivos(String tipoDeDemanda, String tipoDeAtendimento)
	{
		ArrayList<CorrelacaoColunasArquivos> correlacao = new ArrayList<CorrelacaoColunasArquivos>();
		
		if(tipoDeDemanda.equals("CDR"))
		{
			if(tipoDeAtendimento.toUpperCase().equals("EXAME"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_NOME.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_TIPO_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getFormato()));
				
			}
			else if(tipoDeAtendimento.toUpperCase().equals("CONSULTA"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_NOME.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_ESPECIALIDADE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PROCEDIMENTO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_CID.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_TIPO_CONSULTA.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TIPO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_IDADE_DO_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_PRIORIDADE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_OBSERVACAO_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_TELEFONE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getTipo(), ParametrosArquivoDemandaReprimidaCDR.INDICE_COLUNA_MUNICIPIO.getFormato()));
			}
		}
		else if(tipoDeDemanda.equals("Filipeta"))
		{
			if(tipoDeAtendimento.toUpperCase().equals("EXAME"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_NOME.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_TIPO_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_DATA_AGENDA.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_HORARIO_AGENDA.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoFilaCDRExame.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getFormato()));
				
			}
			else if(tipoDeAtendimento.toUpperCase().equals("CONSULTA"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_NOME.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_ESPECIALIDADE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PROCEDIMENTO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_CID.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_CID.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_TIPO_CONSULTA.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TIPO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_IDADE_DO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_IDADE_DO_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_DATA_AGENDA.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_DATA_AGENDA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_HORARIO_AGENDA.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_HORARIO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_PRIORIDADE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_PRIORIDADE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_OBSERVACAO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_OBSERVACAO_STATUS.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_OBSERVACAO_STATUS.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_TELEFONE.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_TELEFONE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoFilaCDRConsulta.INDICE_COLUNA_MUNICIPIO.getIndice(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getTipo(), ParametrosArquivoDemandaReprimidaFilipetasNaoImpressas.INDICE_COLUNA_MUNICIPIO.getFormato()));
			}
		}
		else if(tipoDeDemanda.equals("Regulada"))
		{
			if(tipoDeAtendimento.equals("Agendamentos"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_FICHA.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_CODIGO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_NOME_FICHA.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getIndice(), ParametrosArquivoAgendamentosPendentesRegulada.INDICE_COLUNA_HIPOTESE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getFormato()));
			}
			else if(tipoDeAtendimento.equals("Solicitações"))
			{
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_FICHA.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_FICHA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_PACIENTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_CODIGO_PACIENTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_CODIGO.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_UNIDADE_SOLICITANTE.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_NOME_FICHA.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_NOME_FICHA.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_ESPECIALIDADE_EXAME.getFormato()));
				correlacao.add(new CorrelacaoColunasArquivos(ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getIndice(), ParametrosArquivoSolicitacoesPendentesRegulada.INDICE_COLUNA_HIPOTESE.getIndice(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getTipo(), ParametrosArquivoDemandaReprimidaRegulada.INDICE_COLUNA_HIPOTESE.getFormato()));
			}
		}
			
		
		return correlacao;
	}
	
}
