package dadosGerais;

public enum IdentificadoresPaginaWebSIRESP {

	ID_FRAME_MENU(0, "site"),
	ID_FRAME_COMPONENTES(0, "principal"),
	ID_FRAME_DISTRIBUICAO_COTAS_TABELA_RESULTADOS(0, "frame1"),
	ID_MENU(0, "example"),
	ID_LEITOS_FILTRO_UNIDADE(0, "FLT_CBO_UNIDADE"),
	ID_LEITOS_FILTRO_ESPECIALIDADE(0, "FLT_CBO_SERVICO"),
	ID_LEITOS_FILTRO_DESCRICAO(0, "FLT_DESC_LEITO"),
	ID_LEITOS_FILTRO_STATUS(0, "FLT_CBO_ATIVIDADE"),
	ID_LEITOS_FILTRO_SEXO(0, "FLT_CBO_SEXO"),
	ID_LEITOS_BOTAO_BUSCAR(0, "btnBuscar"),
	ID_LEITOS_BOTAO_CANCELAR(0,"btnCancelar"),
	ID_TABELA_CENSO(0, "tab-listagem"),
	ID_LEITOS_MOTIVO_BLOQUEIO(0,"CBO_MOTIVO_BLOQUEIO"),
	ID_LEITOS_JUSTIFICATIVA_BLOQUEIO(0,"MOTIVO_OUTROS"),
	CLASS_NAME_CADEADO(0, "tooltipleft"),
	NUM_COLUNA_TABELA_CENSO_DESCRICAO_ENFERMARIA(4, "Descrição Enfermaria"),
	NUM_COLUNA_TABELA_CENSO_DESCRICAO_LEITO(5, "Descrição Leito"),
	NAME_LEITOS_BOTAO_DOWNLOAD(0, "btn_excel"),
	NAME_LEITOS_BOTAO_BUSCAR(0, "btn_acao"),
	MOTIVO_BLOQUEIO_ISOLAMENTO(0, "ISOLAMENTO"),
	MOTIVO_BLOQUEIO_AGUARDANDO_PACIENTE(0, "AGUARDANDO PACIENTE"),
	MOTIVO_BLOQUEIO_PROJETO_DE_CIRURGIAS_ELETIVAS(0, "PROJETO DE CIRURGIAS ELETIVAS"),
	MOTIVO_BLOQUEIO_OUTROS(0,"OUTROS"),
	NAME_AMBULATORIAL_BOTAO_OK_ESCOLHER_UNIDADE(0, "escolher"),
	ID_AMBULATORIAL_BOTAO_OK_ESCOLHER_UNIDADE(0, "escolher"),
	ID_AMBULATORIAL_RADIO_UNIDADES(0, "unidade"),
	ID_AMBULATORIAL_CDR_ABA_LISTAR(0, "c_listar"),
	NAME_AMBULATORIAL_CDR_BOTAO_DOWNLOAD(0, "btn_excel"),
	ID_AMBULATORIAL_CDR_FILTRO_TIPO_CONSULTA_EXAME(0, "TIPO_CE"),
	ID_AMBULATORIAL_REGULADA_AGENDAMENTOS_FILTRO_TIPO_CONSULTA_EXAME(0, "FLT_TP_CE"),
	ID_AMBULATORIAL_REGULADA_AGENDAMENTOS_BOTAO_DOWNLOAD(0, "btn_exportaExcel"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_LINK_SELECIONE(0, "lblSelecioneEspExa"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_FILTRO_TIPO_CONSULTA_EXAME(0, "FLT_TP_CE"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_DOWNLOAD(0, "btn_exportaExcel"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_MOVER_SELECIONADOS_PARA_DIREITA(0, "btnMarcarUm"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_MOVER_TODOS_PARA_DIREITA(0, "btnMarcarTodos"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_MOVER_TODOS_PARA_ESQUERDA(0, "btnDesmarcarTodos"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_MOVER_SELECIONADOS_PARA_ESQUERDA(0, "btnDesmarcarUm"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_LIMPAR_SELECAO(0, "btn_limpar1"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_ACEITAR_SELECIONADOS(0, "btn_incluir"),
	VALUE_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_ACEITAR_SELECIONADOS(0, "Aceitar"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_FECHAR_SELECAO_ESPECIALIDADES(0, "btn_fechar"),
	VALUE_AMBULATORIAL_REGULADA_SOLICITACOES_BOTAO_FECHAR_SELECAO_ESPECIALIDADES(0, "Sair"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_LISTAGEM_ESCOLHER_ESPECIALIDADE(0, "FLT_ESP_EXA_DISP"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_LISTAGEM_ESPECIALIDADES_SELECIONADAS(0, "FLT_ESP_EXA"),
	ID_AMBULATORIAL_REGULADA_SOLICITACOES_DIV_ESPERANDO(0, "divProcessando"),
	ID_ABSENTEISMO_MENSAGEM_NENHUM_REGISTRO_ENCONTADO(0, "msgNenhumRegistro"),
	ID_ABSENTEISMO_FILTRO_TIPO_CONSULTA_EXAME(0, "CBO_TIPO"),
	ID_ABSENTEISMO_FILTRO_UNIDADE_EXECUTANTE(0, "CBO_ID_ARVORE"),
	NAME_ABSENTEISMO_FILTRO_DATA_INICIAL(0, "FLT_DATA_INI"),
	NAME_ABSENTEISMO_FILTRO_DATA_FINAL(0, "FLT_DATA_FIM"),
	ID_ABSENTEISMO_FILTRO_ORDENACAO_RELATORIO(0, "ordenacao_relatorio"),
	NAME_ABSENTEISMO_BOTAO_BUSCAR(0, "btn_acao"),
	NAME_ABSENTEISMO_BOTAO_DOWNLOAD(0, "btn_excel"),
	TEXTO_ABSENTEISMO_SELECIONE_ITEM_UNIDADE_EXECUTANTE(0,"- Selecione a Unidade -"),
	
	ID_CONSOLIDADO_MENSAL_TIPO_RELATORIO(0, "FLT_CBO_REL"),
	TEXTO_CONSOLIDADO_MENSAL_RELATORIO_CONSULTAS(0, "Consolidado Mensal - Agendamentos Consulta x Especialidade"),
	TEXTO_CONSOLIDADO_MENSAL_RELATORIO_EXAMES(0, "Consolidado Mensal - Agendamentos Exame x Grupo de Cota"),
	
	ID_CONSOLIDADO_MENSAL_BOTAO_BUSCAR(0, "btn_acao"),
	NAME_CONSOLIDADO_MENSAL_BOTAO_DOWNLOAD(0, "btn_excel"),
	
	NAME_CONSOLIDADO_MENSAL_FILTRO_MES(0, "FLT_MES"),
	NAME_CONSOLIDADO_MENSAL_FILTRO_ANO(0, "FLT_ANO"),
	
	XPATH_CONSOLIDADO_MENSAL_TABELA_RESULTADOS_CONSULTAS(0, "//*[@id=\"formulario\"]/table/tbody/tr[3]/td/table[2]"),
	XPATH_CONSOLIDADO_MENSAL_NENHUM_RESULTADO_ENCONTRADO(0, "//*[@id=\"formulario\"]/table/tbody/tr[3]/td/center/p"),
	
	
	ID_PRODUCAO_EXECUTANTE_TIPO_RELATORIO(0, "FLT_CBO_TIPO"),
	NAME_PRODUCAO_EXECUTANTE_FILTRO_MES(0, "FLT_MES"),
	NAME_PRODUCAO_EXECUTANTE_FILTRO_ANO(0, "FLT_ANO"),
	NAME_PRODUCAO_EXECUTANTE_UNIDADE_SOLICITANTE_PRIMEIRO_NIVEL(0, "CBO_ID_ARVORE_T[2]"),
	NAME_PRODUCAO_EXECUTANTE_UNIDADE_SOLICITANTE_SEGUNDO_NIVEL(0, "CBO_ID_ARVORE_T[3]"),
	NAME_PRODUCAO_EXECUTANTE_UNIDADE_SOLICITANTE_TERCEIRO_NIVEL(0, "CBO_ID_ARVORE_T[4]"),
	
	NAME_PRODUCAO_EXECUTANTE_EXIBIR_RECEPCAO(0, "FLG_MARCA_REC"),
	
	ID_PRODUCAO_EXECUTANTE_BOTAO_BUSCAR(0, "btn_acao"),
	NAME_PRODUCAO_EXECUTANTE_BOTAO_DOWNLOAD(0, "btn_excel"),
	
	TEXTO_PRODUCAO_EXECUTANTE_DRSVII_CAMPINAS(0, "DRS VII - CAMPINAS"),
	TEXTO_PRODUCAO_EXECUTANTE_REGIAO_METROPOLITANO_CAMPINAS(0, "REGIAO DE SAUDE - REGIAO METROPOLITANA DE CAMPINAS"),
	TEXTO_PRODUCAO_EXECUTANTE_SMS_CAMPINAS(0, "SMS - CAMPINAS"),
	
	XPATH_PRODUCAO_EXECUTANTE_TABELA_RESULTADOS(0, "/html/body/form/table/tbody/tr[8]/td/table/tbody/tr/td/table/tbody/tr/td/table[2]"),
	XPATH_PRODUCAO_EXECUTANTE_NENHUM_RESULTADO_ENCONTRADO(0, "/html/body/form/table/tbody/tr[8]/td/table/tbody/tr/td/table/tbody/tr/td/center/span"),
	
	TEXTO_VINCULO_ESTADUAL(0, "ESTADUAL"),
	TEXTO_VINCULO_CONVENIO(0, "CONVÊNIO"),
	TEXTO_VINCULO_PROPRIO(0, "PRÓPRIO"),
	TEXTO_VINCULO_CONTRATO(0, "CONTRATO"),
	
	ID_AGENDA_HORARIOS_FILTRO_TIPO_RELATORIO(0, "CBO_TIPO_HOR"),
	ID_AGENDA_HORARIO_FILTRO_ANO(0, "CBO_ANO"),
	ID_AGENDA_HORARIO_FILTRO_MES(0, "CBO_MES"),
	ID_AGENDA_HORARIO_BOTAO_BUSCAR(0, "btn_acao_buscar"),
	NAME_AGENDA_HORARIO_BOTAO_BUSCAR(0, "btn_acao"),
	
	ID_PACIENTES_SEM_RECEPCAO_FILTRO_TIPO_RELATORIO(0, "FLT_CBO_TIPO"),
	NAME_PACIENTES_SEM_RECEPCAO_FILTRO_DATA_INICIAL(0, "DATA_INI"),
	NAME_PACIENTES_SEM_RECEPCAO_FILTRO_DATA_FINAL(0, "DATA_FIM"),
	NAME_PACIENTES_SEM_RECEPCAO_BOTAO_BUSCAR(0, "btn_acao"),
	
	ID_PACIENTES_SEM_RECEPCAO_FITLRO_UNIDADE(0, "FLT_COD_UNIDADE"),
	
	XPATH_PACIENTES_SEM_RECEPCAO_TABELA_RESULTADOS(0, "/html/body/form/table/tbody/tr[3]/td/table[3]"),
	XPATH_PACIENTES_SEM_RECEPCAO_NENHUM_RESULTADO_ENCONTRADO(0, "//span[@class='dados']"),
	
	XPATH_AGENDA_HORARIO_TABELA_RESULTADOS(0, "//*[@id=\"coluna-conteudo\"]/table[2]/tbody/tr[1]/td/table"),
	XPATH_AGENDA_HORARIO_NENHUM_RESULTADO_ENCONTRADO(0, "//*[@id=\"coluna-conteudo\"]/p"),
	
	ID_DISTRIBUICAO_DE_COTA_FILTRO_TIPO_RELATORIO(0, "FLT_TIPO"),
	ID_DISTRIBUICAO_DE_COTA_FILTRO_ATIVOS(0, "FLT_LISTAGEM"),
	ID_DISTRIBUICAO_DE_COTA_FILTRO_ARVORE(0, "FLT_ID_ARVORE"),
	ID_DISTRIBUICAO_DE_COTA_FILTRO_GRUPO_DE_COTA(0, "FLT_ID_GRUPO_COTA"),
	
	ID_DISTRIBUICAO_DE_COTA_FILTRO_MES(0, "FLT_MES"),
	ID_DISTRIBUICAO_DE_COTA_FILTRO_ANO(0, "FLT_ANO"),
	NAME_DISTRIBUICAO_DE_COTA_BOTAO_BUSCAR(0, "btn_acao"),
	
	TEXTO_DISTRIBUICAO_DE_COTA_ATIVOS_TODAS(0, "Todas"),
	TEXTO_DISTRIBUICAO_DE_COTA_RESULTADO_BLOQUEADOS(0, "BLOQUEADO:"),	
	TEXTO_DISTRIBUICAO_DE_COTA_VALOR_PADRAO_GRUPO_DE_COTA(0, "- Selecione grupo de cota -"),

	XPATH_DISTRIBUICAO_DE_COTA_ARVORE_PRINCIPAL(0, "//*[@id=\"formulario\"]/table[2]/tbody/tr/td[1]/table/tbody/tr[1]/td"),
	//XPATH_DISTRIBUICAO_DE_COTA_TABELA_RESULTADO(0, "/html/body/form/table/tbody/tr[1]/td/table[1]/tbody/tr[1]/td/table/tbody/tr/td[2]"),
	
	XPATH_DISTRIBUICAO_DE_COTA_TABELA_RESULTADO(0, "//*[@id=\"form1\"]/table/tbody/tr[1]/td/table[1]/tbody/tr[1]/td/table/tbody/tr/td[2]"),
	
	NAME_MANUTENCAO_EQUIPAMENTO_GRUPO_DE_COTA(0, "FLT_ID_GRUPO_COTA"),
	NAME_MANUTENCAO_EQUIPAMENTO_LISTAGEM_ATIVOS(0, "FLT_TIPO_LST"),
	NAME_MANUTENCAO_EQUIPAMENTO_BOTAO_BUSCAR(0, "btn_acao"),
	
	TEXTO_MANUTENCAO_EQUIPAMENTO_VALOR_PADRAO_GRUPO_DE_COTA(0, "-- Selecione --"),
	TEXTO_MANUTENCAO_EQUIPAMENTO_LISTAGEM_TODOS(0, "Todos"),
	TEXTO_MANUTENCAO_EQUIPAMENTO_TABELA_RESULTADOS_PRIMEIRA_CELULA(0, "Nome associação"),
	
	XPATH_MANUTENCAO_EQUIPAMENTO_TABELA_RESULTADOS(0, "/html/body/form/table[1]/tbody/tr[2]/td/table[2]/tbody/tr/td/table"),
	
	ID_RELATORIO_CDR_QUALITATIVO_FILTRO_TIPO_RELATORIO(0, "FLT_TIPO_CE"),
	ID_RELATORIO_CDR_QUALITATIVO_FILTRO_DATA_INICIAL(0, "FLT_DT_INICIO"),
	ID_RELATORIO_CDR_QUALITATIVO_FILTRO_DATA_FINAL(0, "FLT_DT_FIM"),
	
	NAME_RELATORIO_CDR_QUALITATIVO_FILTRO_TIPO_CONSULTA(0, "FLT_TP_MARCACAO"),
	TEXTO_RELATORIO_CDR_QUALITATIVO_FILTRO_TIPO_CONSULTA(0, "1 Consulta"),
	
	ID_RELATORIO_CDR_QUALITATIVO_BOTAO_DOWNLOAD(0, "btn_acao"),
	
	NAME_CADASTRO_DEMANDA_POR_RECURSO_TEXT_CODIGO_PACIENTE(0, "FLT_F_COD_PACIENTE"),
	ID_CADASTRO_DEMANDA_POR_RECURSO_FILTRO_ESPECIALIDADE(0, "ID_ESP_EXA"),
	ID_CADASTRO_DEMANDA_POR_RECURSO_FILTRO_TIPO_DEMANDA(0, "TIPO_CE"),
	NAME_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_BUSCAR(0, "Buscar"),
	ID_CADASTRO_DEMANDA_POR_RECURSO_LISTAR_CDR_REGULACOES(0, "c_fila"),
	
	NAME_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_VOLTAR_HISTORICO(0, "btn_voltar"),
	
	VALOR_DINAMICO_LINHA_TABELA_RESULTADOS(0, "#####"),
	
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_NENHUM_RESULTADO_ENCONTRADO(0, "//*[@id=\"formulario\"]/div[4]"),
	
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_TABELA_RESULTADO(0, "//*[@id=\"formulario\"]/table[3]/tbody/tr[1]/td/table"),
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_ACAO_TABELA_RESULTADO(0, "//*[@id=\"formulario\"]/table[3]/tbody/tr[1]/td/table/tbody/tr[" + VALOR_DINAMICO_LINHA_TABELA_RESULTADOS.getTextoIdentificador() + "]/td[2]"),

	XPATH_CADASTRO_DEMANDA_POR_RECURSO_TABELA_REGULACAO_CONSULTA(0, "//*[@id=\"fila_dv\"]/table[2]/tbody/tr[2]/td/table[1]"),
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_ACAO_TABELA_REGULACAO_CONSULTA(0, "//*[@id=\"fila_dv\"]/table[2]/tbody/tr[2]/td/table[1]/tbody/tr[" + VALOR_DINAMICO_LINHA_TABELA_RESULTADOS.getTextoIdentificador() + "]/td[11]/img"),
	
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_TABELA_REGULACAO_EXAME(0, "//*[@id=\"fila_dv\"]/table[2]/tbody/tr[2]/td/table[2]"),
	XPATH_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_ACAO_TABELA_REGULACAO_EXAME(0, "//*[@id=\"fila_dv\"]/table[2]/tbody/tr[2]/td/table[2]/tbody/tr[" + VALOR_DINAMICO_LINHA_TABELA_RESULTADOS.getTextoIdentificador() + "]/td[10]/img"),
	
	ID_CADASTRO_DEMANDA_POR_RECURSO_ALTERACAO_HISTORICO(0, "CBO_ID_MOTIVO"),
	ID_CADASTRO_DEMANDA_POR_RECURSO_OBSERVACAO_ALTERACAO_HISTORICO(0, "OBSERVACAO"),
	NAME_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_REGISTRAR_ALTERACAO_HISTORICO(0, "btn_lancar_historico"),
	NAME_CADASTRO_DEMANDA_POR_RECURSO_BOTAO_CANCELAR_ALTERACAO_HISTORICO(0, "btn_cancelar"),
	TEXTO_CADASTRO_DEMANDA_POR_MOTIVO_ALTERACAO_HISTORICO(0, "Inserção errada"),
	
	TEXTO_CADASTRO_DEMANDA_POR_RECURSO_OBSERVACAO_ALTERACAO_HISTORICO(0, "Paciente transferido para a fila da unidade "),
	TEXTO_CADASTRO_DEMANDA_POR_RECURSO_OBSERVACAO_REMOCAO_POR_DUPLICACAO(0, "Removido por duplicação no processo de importação manual do CDR da Central Reg"),
	
	TEXTO_UNIDADE_CENTRAL_REG_DE_CAMPINAS(0, "CENTRAL REG DE CAMPINAS"),
	TEXTO_USUARIO_IMPORTACAO_MANUAL(0, "IMPORTACAO MANUAL"),
	
	VALOR_ABSENTEISMO_ORDENACAO_RELATORIO_DATA_HORA_AGENDAMENTO(0, "DT_HR_ACAO");
		
	private int indice;
	private String textoIdentificador;
	
	IdentificadoresPaginaWebSIRESP(int indice, String textoIdentificador)
	{
		this.setIndice(indice);
		this.textoIdentificador = textoIdentificador;
	}

	public String getTextoIdentificador() {
		return textoIdentificador;
	}

	public void setTextoIdentificador(String textoIdentificador) {
		this.textoIdentificador = textoIdentificador;
	}

	public int getIndice() {
		return indice;
	}

	public void setIndice(int indice) {
		this.indice = indice;
	}
}
